[package]
name = "scroll-and-sigil-editor-desktop"
version = "0.1.0"
authors = ["Nate M <email>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
minifb = "0.16.0"
editor = { path = "../scroll-sigil-lib" }
